### PR TITLE
134 fix unique constraint error

### PR DESCRIPTION
**Pull request by schultyy**
This PR resolves the issue described in #134.
Under unknown circumstances a Unique Constraint Violation is raised when attempted create a talk and update the user attributes in one step.
This does it in two steps now. At first the talk is created and when this succeeds, user attributes are updated.

### CODE REVIEW

**Comment by bitboxer** [comment]
Is it possible to write a test for this edgecase and prevent that it is happening again?

**Comment by maser** [comment]
:+1:

**Comment by maser** [comment]
@bitboxer I pushed a test.

**Comment by moonglum** [comment]
Thanks for fixing this :smile:

**Pull request merged**
